name: Update Latest Followers

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install required Python packages
        run: |
          pip install requests

      - name: Run getLatestFollowers script
        run: python src/getLatestFollowers.py VoidSon-Stubs ${{ secrets.GITHUB_TOKEN }} README.md

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull --rebase origin master  # Pull and rebase to avoid conflicts
          git add README.md
          git commit -m "Update latest followers"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
